sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
services:
  - docker
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "O6I6EIN+McGzgSYnF1fg/jH4gjBLoYWPS06Ryf9rY/cDzu5g0kt05fz1Re5oWrErC8lURvH/tfs/0Zyx54OWtBUOqT5SelEbg+CgdwSWouyEV3aa1Uwwv1QXlqyXx7X7DQlB3EM8JbZx/YvsSzUaLAdad1Pve1P0p6zSV2CmSx3wPKk5sb+1vND+DquFE6eUmLG62MmCnJiyzmWzo+tfQrDAcE/HUEnQw6w5asG/8eOXav51doz3dw+zVQ5X7R1CZUynUL6PJ6G/gUDNEzTR7BfkxIOfn31K9p7FmjoAlM2yoB9KjLkETCmXxhhMVfoLcWWpqvQqpzqRMUdBiaFf6hV6f7IivKG2xONmCrZyUYpglztikhS9yKVJDFoI+CHC2NjRU5wviZRcA/kRuA5vWFAFKcsEkH+rXAFcjrNezLtvYmiNhwnFs0UAJVs/2mG1gcS5EniGepVmkeQwWBZKLfl8pZvfzyiqf51JSiAZ93IedGezMmZc35QVOZVWsBsMcH5amvtB6PuKs29d3RB8lGm2Wtp6m0GvjYlnhgHjLK9N/1K9KPwI2U0g5kvrWG48Qvsl9h9Ieu/7xLqZPZQaYf0NKjmr2UoRNGncCXDNZtsDgDoxJaZoObx8Y0VFSBXOYCubqGWiMZbZR3xig8WOobqcJdkw/GiTYXreD7h+pSY="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "aKxb5cikoWPpSf+2FArF7RthdhM4HO0XxNC8Du8Oe6oOMvQYx3r85II6ouUcF0311AYAtlVDymq0m/E715bdZEsa/4X/WSeddgUVQKo3w+78PGUJs+OjkKMgHiZ1k86Yx9T2wf9GZacJxYwA7j7C9IbBx2otlrKyEvRIU6wLuC4sp23/kGA5X0Irdd8GZs2hvoUSK+Vlp2D7MmDkqS4B+Pp/rW+8lqG8AM3MyaDdZNhGVS5l3LG9bw1vWxVJmBH6GoOoNwnrGpL7eo1BsK9JPfUcZbJ3AEuEY11bap8Pp17ffj2isBBcWPKHts1DBbZEDi+b9Tz61cftYsX7hoSrWWHWdl427qE6n0Af0ouxJvZRDtdlIq3AeNTyxQL/fSuKiDoDi17Nz+kEYr6U+lNiDfpCq8dSxNTxQCz0bJlU3X3v7TNbw1sknysM+mR5dmU3Z8UQ4OwBv9M4XHesBVKbatLdLBEOFwAyl2l1+hnLyzkiGBxOaSldpEFMw58EWHnIizr9394xtW6AQExmyzLmp3122soUm0ctqyfjPu2Uqwwn6sIqpVIE1RTKLTzDqRWWz7PZou+zPnBTZSYsVosSqbXt4V1Ntmioe0BC5CPok0NaMDB4pbKYrQjnmDWT3Us381fNVi/1U7lPXbThxhLZAezN0Io9DGCfYVUwIZC2qCg="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "CgyX1zuDqyctKhgMDsi7jj/4+9xR+f3xP3HwGKPHA1OvPICWeCubWMRWgSkuiarhkxhDJ1392SP2Y6oSLJ/XR7xsawQSIJojCCalXKA9QHOtc4MB0v6u+vfwkWc4YkNzs/1G03hVvtVYK924670Ayml9fnxfO7Js+ZzPl6U8Bc5om+ybUpkZ0FfmDn4S4rgtQwezDv9Lrg1xt1GGyWlUgDgrrjbp4inhhFs7wJC+mJD88oetUN8hGICgTvVKNuGemW4hhnx4UMc2kPd4HNtmgzxfulilS5R2sULQV38NvilJMGI5hBxkt+9ar4rmnyc74uvsNr/GQYh0t3RfmyvZCDf3SeBJvhCqcc4ZWj+Jh+jUvneb3W7pl1RjGWOQB5dOBk9UoVk+kaeW6/ENnmjRviml9RG41UgKhzdcXPuE1y+3vlstCpKI4BaKTfDsGIjEi+TLjNpCmOnOf68oRsgq9vGSti0pI/KVTvrPMpF6bqQtmuQUab4mbMIDaCjeTUFO9baUu7L7UJR6BF5Ch4RkeDnJuFvUDZX68yMldQfDsVMBvs542ds9aaEIoHFavPl0sWsfO5gbP57QzzckJ31KWyGfamzwnP7RP6MNzA/LGs2Jq68pfe4GWqgjyw1wgHDRCydSUfBtYjFwNXt928lZ9EVQe5x4yiXCcbfM5ADKu78="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "CvDFUrsXKYP2ZE2QLNiSMhIb0gYBLyZT2FF6iQJWL6EBx0Xb5/Or8rDYWx/n10K8OUuLJG7lFe0R2E2crhsLHGotyvGDG2JBC5ZdBhFHYJ9nUZj9nN07u+A0kVPiIVUtXm4uNwY6eagnK3v1xv22gIAkxcCqstifJzbjNNoSGHxxiFeC/i7cvdyTiO09hlJTG8MyQBrklF90/ToeFBt1u6mirTgxJ0PIcbKsSTyCqhyEiwJ60Onv/FRoPx/AmR3TgyCGqYCiQqyu7XP16C65Eb/yI7cJd29W7rjPk8DtyMfrmLAH/0s4njYXrW8g/LfaN2xQTSh/zw+rwJfeZNZbMi9C4UbnKHl+FYkDc3HUNu61k5R67TFjOxfb708gX0ZmR1Stu+Quk+2UalKZ+CHi7dUfXya8Mz06yv63XCcLvMf1/A3sMcVK2pmsRzNLOOBJ4vLGpOv9fNSXAE/sbnKjC14OE0VWrEocv2atdBvP6Bg0NmFdPNZHK7Y2i242WVoY6DeA/mJ5t+gLfkVICNHWrNNrRNUaBZ5vGaYFhyWF0jpd44p1W3lzU7T6jLqfHrp9agKn4RO+IFZEe7u2syc4GvQv3mCqajqsRMPIT5DgZ+FqxhZsGLv1tyQjog6xq5o8eTX61cKS+m8IosnIVb6hkRNApWxfjkSlY/Y2d3XVr0s="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "oQgr3g4/CNbjYvgIbcfvnhaxeYsDiYja95+VzOxp7rfbGTselUo4k27f4H5+97XboZP+4LyGb+leoDai9IUY6exAdrKZz9pJDykDUxQtQHNd5XofsSVf64DpB+TCpmBxxtMwAT0s5O0sOeV5T+cBp4p2lV9I11lrSh+IxmmEo14v/2kueRENSEy2WDjXmuDntVVLI1n43hMWHnhxizQGRf/Uik6xm+HnTm8+4wPe/XKDJXY6DFmnZalXk4E/a2CBYGVWQWRyHAPTD+K963l0FzmvDoI9xXLpN63l48EDonA4aGsvZCkv4gs1VNrpqPxhxr2v5A6MdRyeDtitoisHmbHtGtdJKy1CeY52AIFQs2Clk30ar9YAPEjS/dy+rm13D2Cc9Zim8TmJeDBYKSAmZpRvQ/TvpK2GfFXEkv7LlDOvlQyXAKyr8ll3oU0J6RssP5JHRkbLmdz7KHseOEcA6IKfGl3JqzuvIgWI6bDdKvJYkER3wE5RVzG1s0RkRGNbZ6vciS6HitzNUZI9kw4qGyV0quWGWH8I2SLdfJVzIV2aPpySnbPUa0ho5in5jSdmw/fK6W88b3BSCOoxcju8yxXcjw63IzVKMPNqkE/2I89hApbfVRS3Ia3C0oGShFsHRRB/cZV3N76gcQ1/SXtYMoA/jDuYhvF4YJf02sPS5Ks="
